apiVersion: apps/v1
kind: Deployment
metadata:
  name: Aqukin-deployment
  namespace: Aqukin
  labels:
    app: Aqukin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Aqukin
  template:
    metadata:
      labels:
        app: Aqukin
    spec:
      containers:
      - name: Aqukin-deployment
        image: dealoux/aqukin:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 500Mi
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: Aqukin-secret
              key: BOT_TOKEN
        - name: PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: Aqukin-secret
              key: PUBLIC_KEY
        - name: APP_ID
          valueFrom:
            secretKeyRef:
              name: Aqukin-secret
              key: APP_ID
        - name: REDIS_URI
          valueFrom:
            secretKeyRef:
              name: Aqukin-secret
              key: REDIS_URI
        - name: GUILD_ID
          valueFrom:
            secretKeyRef:
              name: Aqukin-secret
              key: GUILD_ID
        - name: OWNER_ID
          valueFrom:
            secretKeyRef:
              name: Aqukin-secret
              key: OWNER_ID
        - name: INVITE_LINK
          valueFrom:
            secretKeyRef:
              name: Aqukin-secret
              key: INVITE_LINK
        - name: LOGGER_URL
          valueFrom:
            secretKeyRef:
              name: Aqukin-secret
              key: LOGGER_URL
        - name: LOG_LEVEL
          valueFrom:
            secretKeyRef:
              name: Aqukin-secret
              key: LOG_LEVEL
        volumeMounts:
        - name: Aqukin-secret-volume
          mountPath: /usr/src/app/aqukin
          readOnly: true
      volumes:
      - name: Aqukin-secret-volume
        secret:
          secretName: Aqukin-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

---
apiVersion: v1
kind: Secret
metadata:
  name: Aqukin-secret
  namespace: Aqukin
  labels:
    app: Aqukin
type: Opaque
stringData:
  BOT_TOKEN: '{{ bot_token }}'
  PUBLIC_KEY: '{{ public_key }}'
  APP_ID: '{{ app_id }}'
  REDIS_URI: '{{ redis_uri }}'
  GUILD_ID: '{{ guild_id }}'
  OWNER_ID: '{{ owner_id }}'
  INVITE_LINK: '{{ invite_link }}'
  LOGGER_URL: '{{ logger_url }}'
  LOG_LEVEL: '{{ log_level }}'
