apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqukin-deployment
  namespace: aqukin
  labels:
    app: aqukin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqukin
  template:
    metadata:
      labels:
        app: aqukin
    spec:
      containers:
      - name: aqukin-deployment
        image: dealoux/aqukin:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 500Mi
        volumeMounts:
        - name: aqukin-secret-volume
          mountPath: /usr/src/app/aqukin
          readOnly: true
      volumes:
      - name: aqukin-secret-volume
        secret:
          secretName: aqukin-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
---
apiVersion: v1
kind: Secret
metadata:
  name: aqukin-secret
  namespace: aqukin
  labels:
    app: aqukin
type: Opaque
stringData:
  .env: |-
    BOT_TOKEN={{ bot_token }}
    PUBLIC_KEY={{ public_key }}
    APP_ID={{ app_id }}
    REDIS_URI={{ redis_uri }}
    GUILD_ID={{ guild_id }}
    OWNER_ID={{ owner_id }}
    INVITE_LINK={{ invite_link }}
    LOGGER_URL={{ logger_url }}
    LOG_LEVEL={{ log_level }}